feature(module-1): solution task 1-5
js-tasks-ru/jsbasic-20220606_ssmirnoff2018 pull request #2
Opened 2022-06-13 14:28 UTC by Monaizor

2022-06-13 14:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 14:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 18:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 18:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 18:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 20:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 20:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 20:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 20:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-13 21:47 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-14 09:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-14 16:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-14 16:06 UTC, koalex requested changes
Исправить 1-1

2022-06-14 16:06 UTC, koalex commented on 1-module/1-task/index.js
> +
```
function factorial(n) {
   // ваш код...
   let result = 1;
   if (n === 0 || n === 1) {
     return result;
   }

   for (let i = 1; i <= n; i++) {
     result = result * i;
   }

   return result;
 }
```

2022-06-14 16:37 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-06-14 16:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-06-16 07:30 UTC, koalex approved these changes

2022-06-16 07:30 UTC, merged